let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    #"Changed Type" = Table.Group(#"Source", {"Sector", "ADM2_PCODE"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Pivoted Column" = Table.Pivot(#"Changed Type", List.Distinct(#"Changed Type"[Sector]), "Sector", "Count", List.Sum),
    #"Inserted Sum" = Table.AddColumn (#"Pivoted Column", "Grand Total", each List.Sum({[Autres], [Securite Alimentaire], [Coordination], [Habitat], [not defined], [Sante], [WASH], [Protection], [Logistique], [Nutrition], [Agriculture], [Education]}), Int64.Type)
in
    #"Inserted Sum"
